coffeestore/coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    ClientViewSet, ManagerViewSet, TypeOfCoffeeViewSet,
    CoffeeViewSet, OrdersViewSet, SaleViewSet, DepartmentViewSet
)
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('client', ClientViewSet)
router.register('manager', ManagerViewSet)
router.register('typeofcoffee', TypeOfCoffeeViewSet)
router.register('coffee', CoffeeViewSet)
router.register('orders', OrdersViewSet)
router.register('sale', SaleViewSet)
router.register('department', DepartmentViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

coffeestore/coffeestore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tables.urls')),
    path('api/', include('coffee.urls')),
    path('admin/', admin.site.urls),
]

coffeestore/tables/urls.py
from django.urls import path
from .views import ClientListView, CoffeeListView, TypeListView, \
    ManagerListView, DepartmentListView, SaleListView, OrdersListView
from . import views
app_name = 'tables'

urlpatterns = [
    path('', views.index),
    path('client/', ClientListView.as_view(), name='client'),
    path('client/create/', views.client_create, name='client_create'),
    path('client/delete/', views.client_delete, name='client_delete'),

    path('coffee/', CoffeeListView.as_view(), name='coffee'),
    path('coffee/create/', views.coffee_create, name='coffee_create'),
    path('coffee/delete/', views.coffee_delete, name='coffee_delete'),

    path('type/', TypeListView.as_view(), name='type'),
    path('type/create/', views.type_create, name='type_create'),
    path('type/delete/', views.type_delete, name='type_delete'),

    path('manager/', ManagerListView.as_view(), name='manager'),
    path('manager/create/', views.manager_create, name='manager_create'),
    path('manager/delete/', views.manager_delete, name='manager_delete'),

    path('department/', DepartmentListView.as_view(), name='department'),
    path('department/create/', views.department_create, name='department_create'),
    path('department/delete/', views.department_delete, name='department_delete'),

    path('sale/', SaleListView.as_view(), name='sale'),
    path('sale/create/', views.sale_create, name='sale_create'),
    path('sale/delete/', views.sale_delete, name='sale_delete'),

    path('orders/', OrdersListView.as_view(), name='orders'),
    path('orders/create/', views.orders_create, name='orders_create'),
    path('orders/delete/', views.orders_delete, name='orders_delete'),
]

coffeestore/coffee/models.py
from django.db import models


class Client(models.Model):
    client_id = models.IntegerField(db_column='Client_id', primary_key=True)  # Field name made lowercase.
    address = models.TextField(db_column='Address')  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=20)  # Field name made lowercase.
    name = models.TextField(db_column='Name')  # Field name made lowercase.
    email = models.TextField(db_column='Email')  # Field name made lowercase.
    orderedamount = models.IntegerField(db_column='OrderedAmount', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'client'


class TypeOfCoffee(models.Model):
    coffee_code = models.IntegerField(db_column='Coffee_code', primary_key=True)  # Field name made lowercase.
    coffee_type_name = models.TextField(db_column='Coffee_type_name')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'type_of_coffee'


class Coffee(models.Model):
    coffee_code = models.OneToOneField(TypeOfCoffee, on_delete=models.CASCADE, db_column='Coffee_code', primary_key=True)  # Field name made lowercase.
    coffee_name = models.TextField(db_column='Coffee_name')  # Field name made lowercase.
    date_of_manufacture = models.DateField(db_column='Date_of_manufacture')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'coffee'


class Department(models.Model):
    department_number = models.IntegerField(db_column='Department_number', primary_key=True)  # Field name made lowercase.
    department_name = models.TextField(db_column='Department_name')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'department'


class Manager(models.Model):
    manager_service_number = models.IntegerField(db_column='Manager_service_number', primary_key=True)  # Field name made lowercase.
    department_number = models.ForeignKey(Department, models.DO_NOTHING, db_column='Department_number')  # Field name made lowercase.
    name = models.TextField(db_column='Name')  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=20)  # Field name made lowercase.
    email = models.TextField(db_column='Email')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'manager'


class Orders(models.Model):
    order_number = models.IntegerField(db_column='Order_number', primary_key=True)  # Field name made lowercase.
    coffee_code = models.ForeignKey(Coffee, models.DO_NOTHING, db_column='Coffee_code')  # Field name made lowercase.
    client_number = models.ForeignKey(Client, models.DO_NOTHING, db_column='Client_number')  # Field name made lowercase.
    order_date = models.DateField(db_column='Order_date')  # Field name made lowercase.
    order_amount = models.IntegerField(db_column='Order_amount')  # Field name made lowercase.
    execution_date = models.DateField(db_column='Execution_date')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'orders'
        unique_together = (('order_number', 'coffee_code', 'client_number'),)


class Sale(models.Model):
    invoice_number = models.IntegerField(db_column='Invoice_number', primary_key=True)  # Field name made lowercase.
    coffee_code = models.ForeignKey(Coffee, models.DO_NOTHING, db_column='Coffee_code')  # Field name made lowercase.
    manager_service_number = models.ForeignKey(Manager, models.DO_NOTHING, db_column='Manager_service_number')  # Field name made lowercase.
    date_of_sale = models.DateField(db_column='Date_of_sale')  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity')  # Field name made lowercase.
    sale_amount = models.IntegerField(db_column='Sale_amount')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'sale'
        unique_together = (('invoice_number', 'coffee_code', 'manager_service_number'),)

coffeestore/coffee/views.py
from .models import (
    Client, Manager, Coffee,
    TypeOfCoffee, Orders, Sale, Department
)
from rest_framework.viewsets import ModelViewSet

from .serializers import (
    ClientSerializer, ManagerSerializer, CoffeeSerializer,
    TypeOfCoffeeSerializer, OrdersSerializer, SaleSerializer,
    DepartmentSerializer
)
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter


class ClientViewSet(ModelViewSet):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer

    filter_backends = (DjangoFilterBackend, SearchFilter,)
    filterset_fields = '__all__'
    search_fields = ('name',)


class ManagerViewSet(ModelViewSet):
    queryset = Manager.objects.all()
    serializer_class = ManagerSerializer

    filter_backends = (DjangoFilterBackend, SearchFilter,)
    filterset_fields = '__all__'
    search_fields = ('name',)


class CoffeeViewSet(ModelViewSet):
    queryset = Coffee.objects.all()
    serializer_class = CoffeeSerializer

    filter_backends = (DjangoFilterBackend, SearchFilter,)
    filterset_fields = '__all__'
    search_fields = ('coffee_name',)


class TypeOfCoffeeViewSet(ModelViewSet):
    queryset = TypeOfCoffee.objects.all()
    serializer_class = TypeOfCoffeeSerializer

    filter_backends = (DjangoFilterBackend, SearchFilter,)
    filterset_fields = '__all__'
    search_fields = ('coffee_type_name',)


class OrdersViewSet(ModelViewSet):
    queryset = Orders.objects.all()
    serializer_class = OrdersSerializer

    filter_backends = (DjangoFilterBackend,)
    filterset_fields = '__all__'


class SaleViewSet(ModelViewSet):
    queryset = Sale.objects.all()
    serializer_class = SaleSerializer

    filter_backends = (DjangoFilterBackend,)
    filterset_fields = '__all__'


class DepartmentViewSet(ModelViewSet):
    queryset = Department.objects.all()
    serializer_class = DepartmentSerializer

    filter_backends = (DjangoFilterBackend,)
    filterset_fields = '__all__'

coffeestore/templates/coffee/coffee_create.html
<!doctype html>
<html>
    <head>
        <title>Coffee</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">

            <div class="card-body">

          <form method="post" enctype="multipart/form-data" action="{% url 'tables:coffee_create' %}">
            {% csrf_token %}

            {% for field in form %}
                {% include 'includes/form_fields.html' %}
            {% endfor %}

            <button type="submit" class="btn btn-primary">
                Сохранить
            </button>
          </form>
        </div>
          </div>
        </div>
      </div>
    </div>
   </body>
</html>

coffeestore/templates/coffee/coffee_delete.html
<!doctype html>
<html>
    <head>
        <title>Coffee</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">

            <div class="card-body">

          <form method="post" enctype="multipart/form-data" action="{% url 'tables:coffee_delete' %}">
            {% csrf_token %}

            {% for field in form %}
                {% include 'includes/form_fields.html' %}
            {% endfor %}

            <button type="submit" class="btn btn-primary">
                Удалить
            </button>
          </form>
        </div>
          </div>
        </div>
      </div>
    </div>
   </body>
</html>

coffeestore/templates/coffee/coffee_list.html
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
<!doctype html>
<html>
    <head>
        <title>Coffee</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>

    <body>
        <div class="container py-5">
            <br>
            <div>
                <a href="/">На главную</a>
            </div>
            <br>
            <div class="row justify-content-center">
            {% if filter %}
                <form method="get" class="form form-inline">
                    {% bootstrap_form filter.form layout='inline' %}
                    {% bootstrap_button 'Поиск' %}
                </form>
            {% endif %}
            {% render_table table 'django_tables2/bootstrap.html' %}
            <a href="create/">Добавить запись</a> <br><br>
            <a href="delete/">Удалить запись</a>
            </div>
        </div>
    </body>
</html>